version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        UID: $UID
        GUID: $GUID
    links:
      - php74
    ports:
      - $PORT_HTTP:80
      - $PORT_HTTPS:443
    volumes:
      - ./shared/logs/nginx:/var/log/nginx
      - ./shared:/var/www
    networks:
      default:
        aliases:
          - dasboard.loc
      dash_net:
        ipv4_address: 172.99.0.1      
  php74:
    restart: always
    build:
      context: ./docker/php74
      dockerfile: Dockerfile
      args:
        UID: $UID
        GUID: $GUID
    links:
      - mysql
    volumes:
      - ./shared:/var/www
      - ./docker/php74/etc:/usr/local/etc
    working_dir: /var/www/app
    expose:
      - 9001
    extra_hosts:
      - "dasboard.loc:172.99.0.1"
    networks:
      dash_net:
        ipv4_address: 172.99.0.2      
  mysql:
    restart: always
    image: "mysql:8.0"
    volumes:
      - ./shared/mysql:/var/lib/mysql
    ports:
      - $DB_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: dash
      MYSQL_DATABASE: dash
      MYSQL_USER: dash
      MYSQL_PASSWORD: dash
    networks:
      dash_net:
        ipv4_address: 172.99.0.10      
networks:
  dash_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.99.0.0/24
